import Header from '@front/components/header/header';
import ThemeProvider from '@front/components/themeProvider/themeProvider';
import '@location-tips/location-tips-uikit/styles/index.css';
import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider />
        <Header />
        {children}
      </body>
    </html>
  );
}
