export const CATEGORIES = [
  'Cemetery',
  'Farm',
  'Industrial Area',
  'Residential Area',
  'Park',
  'National Park',
  'Beach',
  'Campground',
  'Educational Institution',
  'Healthcare Facility',
  'Airport',
  'Transport Station',
  'Shopping Area',
  'Dining Area',
  'Hotel',
  'Cultural Site',
  'Library',
  'Entertainment Venue',
  'Sports Facility',
  'Marina/Port',
  'Office/Government Building',
  'Place of Worship',
  'Transportation Infrastructure',
  'Animal/Nature Attraction',
  'Resort',
  'Beverage Production Facility',
  'Gas Station',
  'Post Office',
  'Financial Institution',
  'Pharmacy',
  'Fire Station',
  'Police Station',
  'Courthouse',
  'Diplomatic Facility',
  'Community/Convention Center',
  'Waste Management Facility',
  'Construction Site',
  'Extraction Site',
  'Lighthouse',
  'Observatory',
  'Energy Production Site',
  'Dockyard',
  'Rest Area',
  'Monument/Plaza',
  'Nature',
  'Abandoned',
  'Other',
];
