# Define substitutions (optional)
substitutions:
  # Replace with the tag of your base image
  _BASE_IMAGE: gcr.io/cloud-builders/docker
  _LOCATION: us-central1
  _BACK_REPOSITORY: location-tips-back
  _FRONT_REPOSITORY: location-tips-front
  _IMAGE: gcr.io/cloud-builders/docker

steps:
- name: $_BASE_IMAGE
  args: ['echo', '$$PERSONAL_ACCESS_TOKEN']
- name: $_BASE_IMAGE
  args: ['echo', '$PERSONAL_ACCESS_TOKEN']
- name: $_BASE_IMAGE
  args: ['build', '--build-arg', 'PERSONAL_ACCESS_TOKEN=$$PERSONAL_ACCESS_TOKEN', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}', '-f', '.Dockerfile', '.', '--progress', 'plain']
- name: $_BASE_IMAGE
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}', '-f', '.Dockerfile-be', '.', '--progress', 'plain']
- name: $_BASE_IMAGE
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_FRONT_REPOSITORY}/${_IMAGE}', '-f', '.Dockerfile-fe', '.', '--progress', 'plain']
- name: $_BASE_IMAGE
  args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}']
- name: $_BASE_IMAGE
  args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_FRONT_REPOSITORY}/${_IMAGE}']
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_FRONT_REPOSITORY}/${_IMAGE}'

availableSecrets:
  secretManager:
  - versionName: projects/1038437023281/secrets/PERSONAL_ACCESS_TOKEN/versions/latest
    env: 'PERSONAL_ACCESS_TOKEN'
