# Define substitutions (optional)
substitutions:
  # Replace with the tag of your base image
  _LOCATION: us-central1
  _BASE_REPOSITORY: location-tips-base
  _BACK_REPOSITORY: location-tips-back
  _FRONT_REPOSITORY: location-tips-front
  _IMAGE: gcr.io/cloud-builders/docker

steps:
  - name: $_BASE_REPOSITORY
    secretEnv: ['PERSONAL_ACCESS_TOKEN']
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build --build-arg NPM_AUTH_TOKEN=$$PERSONAL_ACCESS_TOKEN -t ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BASE_REPOSITORY}/${_IMAGE} -f .Dockerfile . --progress plain',
      ]
  - name: $_BASE_REPOSITORY
    args:
      [
        'push',
        '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BASE_REPOSITORY}/${_IMAGE}',
      ]
  - name: $_BACK_REPOSITORY
    args:
      [
        'build',
        '--build-arg',
        'IMG_FROM=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BASE_REPOSITORY}/${_IMAGE}',
        '-t',
        '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}',
        '-f',
        '.Dockerfile-be',
        '.',
        '--progress',
        'plain',
      ]
  - name: $_BACK_REPOSITORY
    args:
      [
        'push',
        '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}',
      ]
  - name: $_FRONT_REPOSITORY
    args:
      [
        'build',
        '--build-arg',
        'IMG_FROM=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BASE_REPOSITORY}/${_IMAGE}',
        '-t',
        '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_FRONT_REPOSITORY}/${_IMAGE}',
        '-f',
        '.Dockerfile-fe',
        '.',
        '--progress',
        'plain',
      ]
  - name: $_FRONT_REPOSITORY
    args:
      [
        'push',
        '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_FRONT_REPOSITORY}/${_IMAGE}',
      ]
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BASE_REPOSITORY}/${_IMAGE}'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_BACK_REPOSITORY}/${_IMAGE}'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_FRONT_REPOSITORY}/${_IMAGE}'

availableSecrets:
  secretManager:
    - versionName: projects/1038437023281/secrets/PERSONAL_ACCESS_TOKEN/versions/2
      env: 'PERSONAL_ACCESS_TOKEN'
